[profile.release]
debug = true

[workspace]
members = [
  "components/builder-api-client",
  "components/builder-depot-client",
  "components/butterfly",
  "components/butterfly-test",
  "components/common",
  "components/eventsrv",
  "components/eventsrv-client",
  "components/github-api-client",
  "components/hab",
  "components/hab-butterfly",
  "components/http-client",
  "components/launcher",
  "components/launcher-client",
  "components/launcher-protocol",
  "components/pkg-export-docker",
  "components/pkg-export-helm",
  "components/pkg-export-kubernetes",
  "components/pkg-export-tar",
  "components/segment-api-client",
  "components/sup"
]

[patch."https://github.com/habitat-sh/core.git"]
habitat_core = {path = "./core/components/core"}
habitat_win_users = {path = "./core/components/win-users"}
