[package]
name = "bitbucket-api-client"
version = "0.0.0"
authors = ["Josh Black <raskchanky@gmail.com>"]
description = "Bitbucket HTTP API Client"
workspace = "../../"

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"

[dependencies.habitat_http_client]
path = "../http-client"
